// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBqpnQllJH2FkT52f6pn1_crruHGCCRz0',
    appId: '1:11514683051:web:236b79837ef857d8f821ee',
    messagingSenderId: '11514683051',
    projectId: 'note-app-f09a9',
    authDomain: 'note-app-f09a9.firebaseapp.com',
    storageBucket: 'note-app-f09a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy0dqipJpwHrdiulRWpdD7BYh3NheHnXw',
    appId: '1:11514683051:android:6d019de96867a5d3f821ee',
    messagingSenderId: '11514683051',
    projectId: 'note-app-f09a9',
    storageBucket: 'note-app-f09a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnXkf0jnMgCRMUBldh4fOtmnrIQM6AdRc',
    appId: '1:11514683051:ios:c73a41c2b79bea68f821ee',
    messagingSenderId: '11514683051',
    projectId: 'note-app-f09a9',
    storageBucket: 'note-app-f09a9.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnXkf0jnMgCRMUBldh4fOtmnrIQM6AdRc',
    appId: '1:11514683051:ios:c73a41c2b79bea68f821ee',
    messagingSenderId: '11514683051',
    projectId: 'note-app-f09a9',
    storageBucket: 'note-app-f09a9.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBqpnQllJH2FkT52f6pn1_crruHGCCRz0',
    appId: '1:11514683051:web:83cc9e6736fc5033f821ee',
    messagingSenderId: '11514683051',
    projectId: 'note-app-f09a9',
    authDomain: 'note-app-f09a9.firebaseapp.com',
    storageBucket: 'note-app-f09a9.firebasestorage.app',
  );

}